### PR TITLE
report: clarify --platform error and add Hyper-V build note

### LINKED ISSUE #103: Failure to fetch report from vTPM in Azure CVM because Hyper-V is hidden
## Summary
* The command `snpguest report ... --platform` should fetch a vTPM-backed platform attestation report on Azure Confidential VMs (feature was added in PR #16).
* Azure CVM (with AMD SEV-SNP) now hides *not only `dev/sev-guest` but Hyper-V* from the guest OS.
* `src/report.rs` therefore bails out with [L80-83](https://github.com/virtee/snpguest/blob/cdddfd41b290c3e64be70e4009c1478f46925b78/src/report.rs#L80-83)
  ```rust
  if self.platform && !hyperv {
      return Err(anyhow!("--platform enabled yet Hyper-V guest not detected (not allowed). Consult man page."));
  }
  ```
  even though vTPM NV-read would succeed:
  ```bash
  sudo tpm2_nvread -C o 0x01400001 > azure-report.bin
  dd if=azure-report.bin skip=32 bs=1 count=1184 of=report.bin
  ```

### Reference
[Azure Confidential VM guest attestation design detail](https://github.com/MicrosoftDocs/azure-docs/blob/3e5d9de5bdfa5c09f4ad9f6b7f5295e7719b2885/articles/confidential-computing/guest-attestation-confidential-virtual-machines-design.md)

### Environment
Azure CVMs with
* Size family: Standard_DC2as_v5
* OS image: Ubuntu Server 24.04 LTS (Confidential VM) - x64 Gen 2.

### Code
```bash
sudo snpguest report report.bin request.bin --platform
```
### Results
```plaintext
ERROR: --platform enabled yet Hyper-V guest not detected (not allowed). Consult man page.
Error: --platform enabled yet Hyper-V guest not detected (not allowed). Consult man page.
```

### PR DESCRIPTION
**Pull request by hyperfinitism**
Fixes #103 

* When snpguest is compiled without the `hyperv` Cargo feature, `--platform` aborts—but the old message implied no Hyper-V guest was present.

* This patch gates the error string with cfg:
  | build | new message |
  | :-- | :-- |
  | with hyperv | --platform enabled yet Hyper-V guest with SEV-SNP isolation not detected (not allowed). |
  | without hyperv | --platform requires a binary built with --features hyperv. |

* No functional change for feature-enabled builds; only error text.

* README.md now adds a short “Building for Azure CVMs” note, because Azure hides `/dev/sev-guest` and needs `--platform` + `--features hyperv`.

# Tests

## Test table
| build / host | expected output |
| :-- | :-- |
| with hyperv / AWS EC2 (no Hyper-V) | ERROR: --platform enabled yet Hyper-V guest with SEV-SNP isolation not detected (not allowed). |
| with hyperv / Azure CVM with SEV-SNP (Hyper-V) | None (report fetch succeeds) | 
| with hyperv / Azure CVM with TDX (Hyper-V) | ERROR: --platform enabled yet Hyper-V guest with SEV-SNP isolation not detected (not allowed). | 
| without hyperv / any host | ERROR: --platform requires a binary built with --features hyperv. |

### build WITH hyperv
```bash
sudo apt update
sudo apt install -y libtss2-dev pkg-config

git clone https://github.com/hyperfinitism/snpguest -b fix-hyperv-support
cd snpguest
cargo build --features hyperv
sudo ./target/debug/snpguest report report.bin request.bin --vmpl 0 --platform
```

### built WIHTOUT hyperv
```bash
git clone https://github.com/hyperfinitism/snpguest -b fix-hyperv-support
cd snpguest
cargo build
sudo ./target/debug/snpguest report report.bin request.bin --vmpl 0 --platform
```

Both paths produce the messages shown above.

### CODE REVIEW

File: src/report.rs [hunk 1]
```diff
@@ -78,7 +78,17 @@ impl ReportArgs {
...
+            {
+                return Err(anyhow!("--platform enabled yet Hyper-V guest with SEV-SNP isolation not detected (not allowed)."));
+            }
+
+            #[cfg(not(feature = "hyperv"))]
+            {
+                return Err(anyhow!(
+                    "--platform requires a binary built with --features hyperv."
+                ));
+            }
```
Comment (tylerfanelli) [inline src/report.rs:91]:
```suggestion
            #[cfg(feature = "hyperv")]
            let msg = "--platform enabled yet Hyper-V guest with SEV-SNP isolation not detected (not allowed)";
            #[cfg(not(feature = "hyperv"))]
            let msg = "--platform requires a binary built with --features hyperv";
            
            return Err(anyhow!(msg));
```

**Review by tylerfanelli — CHANGES_REQUESTED** [review]

**Review by tylerfanelli — APPROVED** [review]
LGTM, thanks for addressing this.

**Review by larrydewey — APPROVED** [review]
